//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class cityEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string __ID = "id";
        
        /// <summary>cityID</summary>
        public const string __CITYID = "cityID";
        
        /// <summary>city</summary>
        public const string __CITY = "city";
        
        /// <summary>father</summary>
        public const string __FATHER = "father";
        
        private int m_id;
        
        private string m_cityID;
        
        private string m_city;
        
        private string m_father;
        
        /// <summary>构造函数</summary>
        public cityEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性cityID </summary>
        public string cityID
        {
            get
            {
                return this.m_cityID;
            }
            set
            {
                this.m_cityID = value;
            }
        }
        
        /// <summary>属性city </summary>
        public string city
        {
            get
            {
                return this.m_city;
            }
            set
            {
                this.m_city = value;
            }
        }
        
        /// <summary>属性father </summary>
        public string father
        {
            get
            {
                return this.m_father;
            }
            set
            {
                this.m_father = value;
            }
        }
    }
    
    /// cityEntity执行类
    public abstract class cityEntityAction
    {
        
        private cityEntityAction()
        {
        }
        
        public static void Save(cityEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static cityEntity RetrieveAcityEntity(int id)
        {
            cityEntity obj=new cityEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrievecityEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(cityEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetcityEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(cityEntity));
            return rc.AsDataTable();
        }
    }
}
