//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class provinceEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string __ID = "id";
        
        /// <summary>provinceID</summary>
        public const string __PROVINCEID = "provinceID";
        
        /// <summary>province</summary>
        public const string __PROVINCE = "province";
        
        private int m_id;
        
        private string m_provinceID;
        
        private string m_province;
        
        /// <summary>构造函数</summary>
        public provinceEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性provinceID </summary>
        public string provinceID
        {
            get
            {
                return this.m_provinceID;
            }
            set
            {
                this.m_provinceID = value;
            }
        }
        
        /// <summary>属性province </summary>
        public string province
        {
            get
            {
                return this.m_province;
            }
            set
            {
                this.m_province = value;
            }
        }
    }
    
    /// provinceEntity执行类
    public abstract class provinceEntityAction
    {
        
        private provinceEntityAction()
        {
        }
        
        public static void Save(provinceEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static provinceEntity RetrieveAprovinceEntity(int id)
        {
            provinceEntity obj=new provinceEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveprovinceEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(provinceEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetprovinceEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(provinceEntity));
            return rc.AsDataTable();
        }
    }
}
