//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_UserFriendsEntity : EntityObject
    {
        
        /// <summary>Id</summary>
        public const string __ID = "Id";
        
        /// <summary>OwnerId</summary>
        public const string __OWNERID = "OwnerId";
        
        /// <summary>OwnerName</summary>
        public const string __OWNERNAME = "OwnerName";
        
        /// <summary>FriendId</summary>
        public const string __FRIENDID = "FriendId";
        
        /// <summary>FriendName</summary>
        public const string __FRIENDNAME = "FriendName";
        
        /// <summary>AddDate</summary>
        public const string __ADDDATE = "AddDate";
        
        /// <summary>FriendDesc</summary>
        public const string __FRIENDDESC = "FriendDesc";
        
        private int m_Id;
        
        private int m_OwnerId;
        
        private string m_OwnerName;
        
        private int m_FriendId;
        
        private string m_FriendName;
        
        private System.DateTime m_AddDate = DateTime.MinValue;
        
        private string m_FriendDesc;
        
        /// <summary>构造函数</summary>
        public XiHuan_UserFriendsEntity()
        {
        }
        
        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }
        
        /// <summary>属性OwnerId </summary>
        public int OwnerId
        {
            get
            {
                return this.m_OwnerId;
            }
            set
            {
                this.m_OwnerId = value;
            }
        }
        
        /// <summary>属性OwnerName </summary>
        public string OwnerName
        {
            get
            {
                return this.m_OwnerName;
            }
            set
            {
                this.m_OwnerName = value;
            }
        }
        
        /// <summary>属性FriendId </summary>
        public int FriendId
        {
            get
            {
                return this.m_FriendId;
            }
            set
            {
                this.m_FriendId = value;
            }
        }
        
        /// <summary>属性FriendName </summary>
        public string FriendName
        {
            get
            {
                return this.m_FriendName;
            }
            set
            {
                this.m_FriendName = value;
            }
        }
        
        /// <summary>属性AddDate </summary>
        public System.DateTime AddDate
        {
            get
            {
                return this.m_AddDate;
            }
            set
            {
                this.m_AddDate = value;
            }
        }
        
        /// <summary>属性FriendDesc </summary>
        public string FriendDesc
        {
            get
            {
                return this.m_FriendDesc;
            }
            set
            {
                this.m_FriendDesc = value;
            }
        }
    }
    
    /// XiHuan_UserFriendsEntity执行类
    public abstract class XiHuan_UserFriendsEntityAction
    {
        
        private XiHuan_UserFriendsEntityAction()
        {
        }
        
        public static void Save(XiHuan_UserFriendsEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_UserFriendsEntity RetrieveAXiHuan_UserFriendsEntity(int Id)
        {
            XiHuan_UserFriendsEntity obj=new XiHuan_UserFriendsEntity();
            obj.Id=Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_UserFriendsEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_UserFriendsEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_UserFriendsEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_UserFriendsEntity));
            return rc.AsDataTable();
        }
    }
}
