//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By�?SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By�?Administrator
//             Created Time�?2009-4-19 15:36:36
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;


    /// <summary>该类的摘要说�?/summary>
    [Serializable()]
    public class XiHuan_UserGoodsEntity : EntityObject
    {

        /// <summary>Id</summary>
        public const string __ID = "Id";

        /// <summary>OwnerId</summary>
        public const string __OWNERID = "OwnerId";

        /// <summary>OwnerName</summary>
        public const string __OWNERNAME = "OwnerName";

        /// <summary>Name</summary>
        public const string __NAME = "Name";

        /// <summary>TypeId</summary>
        public const string __TYPEID = "TypeId";

        /// <summary>ChildId</summary>
        public const string __CHILDID = "ChildId";

        /// <summary>NewDeep</summary>
        public const string __NEWDEEP = "NewDeep";

        /// <summary>OnlyCityChange</summary>
        public const string __OnlyCityChange = "OnlyCityChange";

        /// <summary>OnlyCityChange</summary>
        public const string __OnlySchoolChange = "OnlySchoolChange";

        /// <summary>ViewCount</summary>
        public const string __VIEWCOUNT = "ViewCount";

        /// <summary>Description</summary>
        public const string __DESCRIPTION = "Description";

        /// <summary>HopeToChangeTypeId</summary>
        public const string __HOPETOCHANGETYPEID = "HopeToChangeTypeId";

        /// <summary>HopeToChangeChildTypeId</summary>
        public const string __HOPETOCHANGECHILDTYPEID = "HopeToChangeChildTypeId";

        /// <summary>HopeToChangeDesc</summary>
        public const string __HOPETOCHANGEDESC = "HopeToChangeDesc";

        /// <summary>IsHavePhoto</summary>
        public const string __ISHAVEPHOTO = "IsHavePhoto";

        /// <summary>DefaultPhoto</summary>
        public const string __DEFAULTPHOTO = "DefaultPhoto";

        /// <summary>ProvinceId</summary>
        public const string __PROVINCEID = "ProvinceId";

        /// <summary>ProvinceName</summary>
        public const string __PROVINCENAME = "ProvinceName";

        /// <summary>CityId</summary>
        public const string __CITYID = "CityId";

        /// <summary>CityName</summary>
        public const string __CITYNAME = "CityName";

        /// <summary>AreaId</summary>
        public const string __AREAID = "AreaId";

        /// <summary>AreaName</summary>
        public const string __AREANAME = "AreaName";

        /// <summary>SchoolId</summary>
        public const string __SCHOOLID = "SchoolId";

        /// <summary>SchoolName</summary>
        public const string __SCHOOLNAME = "SchoolName";

        /// <summary>GoodState</summary>
        public const string __GOODSTATE = "GoodState";

        /// <summary>IsTJ</summary>
        public const string __ISTJ = "IsTJ";

        /// <summary>CreateDate</summary>
        public const string __CREATEDATE = "CreateDate";

        /// <summary>DetailUrl</summary>
        public const string __DETAILURL = "DetailUrl";

        /// <summary>IsChecked</summary>
        public const string @__ISCHECKED = "IsChecked";

        private int m_Id;

        private int m_OwnerId;

        private string m_OwnerName;

        private string m_Name;

        private int m_TypeId;

        private int m_ChildId;

        private System.Byte m_NewDeep;

        private System.Byte m_OnlyCityChange;

        private System.Byte m_OnlySchoolChange;

        private int m_ViewCount;

        private string m_Description;

        private int m_HopeToChangeTypeId;

        private int m_HopeToChangeChildTypeId;

        private string m_HopeToChangeDesc;

        private System.Byte m_IsHavePhoto;

        private string m_DefaultPhoto;

        private int m_ProvinceId;

        private string m_ProvinceName;

        private int m_CityId;

        private string m_CityName;

        private int m_AreaId;

        private string m_AreaName;

        private int m_SchoolId;

        private string m_SchoolName;

        private System.Byte m_GoodState;

        private System.Byte m_IsTJ;

        private System.DateTime m_CreateDate = DateTime.MinValue;

        private string m_DetailUrl;

        private byte m_IsChecked;

        /// <summary>构造函�?/summary>
        public XiHuan_UserGoodsEntity()
        {
        }

        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }

        /// <summary>属性OwnerId </summary>
        public int OwnerId
        {
            get
            {
                return this.m_OwnerId;
            }
            set
            {
                this.m_OwnerId = value;
            }
        }

        /// <summary>属性OwnerName </summary>
        public string OwnerName
        {
            get
            {
                return this.m_OwnerName;
            }
            set
            {
                this.m_OwnerName = value;
            }
        }

        /// <summary>属性Name </summary>
        public string Name
        {
            get
            {
                return this.m_Name;
            }
            set
            {
                this.m_Name = value;
            }
        }

        /// <summary>属性TypeId </summary>
        public int TypeId
        {
            get
            {
                return this.m_TypeId;
            }
            set
            {
                this.m_TypeId = value;
            }
        }

        /// <summary>属性ChildId </summary>
        public int ChildId
        {
            get
            {
                return this.m_ChildId;
            }
            set
            {
                this.m_ChildId = value;
            }
        }

        /// <summary>属性NewDeep </summary>
        public byte NewDeep
        {
            get
            {
                return this.m_NewDeep;
            }
            set
            {
                this.m_NewDeep = value;
            }
        }

        /// <summary>OnlyCityChange </summary>
        public System.Byte OnlyCityChange
        {
            get
            {
                return this.m_OnlyCityChange;
            }
            set
            {
                this.m_OnlyCityChange = value;
            }
        }

        /// <summary>OnlySchoolChange </summary>
        public System.Byte OnlySchoolChange
        {
            get
            {
                return this.m_OnlySchoolChange;
            }
            set
            {
                this.m_OnlySchoolChange = value;
            }
        }

        /// <summary>属性ViewCount </summary>
        public int ViewCount
        {
            get
            {
                return this.m_ViewCount;
            }
            set
            {
                this.m_ViewCount = value;
            }
        }

        /// <summary>属性Description </summary>
        public string Description
        {
            get
            {
                return this.m_Description;
            }
            set
            {
                this.m_Description = value;
            }
        }

        /// <summary>属性HopeToChangeTypeId </summary>
        public int HopeToChangeTypeId
        {
            get
            {
                return this.m_HopeToChangeTypeId;
            }
            set
            {
                this.m_HopeToChangeTypeId = value;
            }
        }

        /// <summary>属性HopeToChangeChildTypeId </summary>
        public int HopeToChangeChildTypeId
        {
            get
            {
                return this.m_HopeToChangeChildTypeId;
            }
            set
            {
                this.m_HopeToChangeChildTypeId = value;
            }
        }

        /// <summary>属性HopeToChangeDesc </summary>
        public string HopeToChangeDesc
        {
            get
            {
                return this.m_HopeToChangeDesc;
            }
            set
            {
                this.m_HopeToChangeDesc = value;
            }
        }

        /// <summary>属性IsHavePhoto </summary>
        public System.Byte IsHavePhoto
        {
            get
            {
                return this.m_IsHavePhoto;
            }
            set
            {
                this.m_IsHavePhoto = value;
            }
        }

        /// <summary>属性DefaultPhoto </summary>
        public string DefaultPhoto
        {
            get
            {
                return this.m_DefaultPhoto;
            }
            set
            {
                this.m_DefaultPhoto = value;
            }
        }

        /// <summary>属性ProvinceId </summary>
        public int ProvinceId
        {
            get
            {
                return this.m_ProvinceId;
            }
            set
            {
                this.m_ProvinceId = value;
            }
        }

        /// <summary>属性ProvinceName </summary>
        public string ProvinceName
        {
            get
            {
                return this.m_ProvinceName;
            }
            set
            {
                this.m_ProvinceName = value;
            }
        }

        /// <summary>属性CityId </summary>
        public int CityId
        {
            get
            {
                return this.m_CityId;
            }
            set
            {
                this.m_CityId = value;
            }
        }

        /// <summary>属性CityName </summary>
        public string CityName
        {
            get
            {
                return this.m_CityName;
            }
            set
            {
                this.m_CityName = value;
            }
        }

        /// <summary>属性AreaId </summary>
        public int AreaId
        {
            get
            {
                return this.m_AreaId;
            }
            set
            {
                this.m_AreaId = value;
            }
        }

        /// <summary>属性AreaName </summary>
        public string AreaName
        {
            get
            {
                return this.m_AreaName;
            }
            set
            {
                this.m_AreaName = value;
            }
        }

        /// <summary>属性SchoolId </summary>
        public int SchoolId
        {
            get
            {
                return this.m_SchoolId;
            }
            set
            {
                this.m_SchoolId = value;
            }
        }

        /// <summary>属性SchoolName </summary>
        public string SchoolName
        {
            get
            {
                return this.m_SchoolName;
            }
            set
            {
                this.m_SchoolName = value;
            }
        }

        /// <summary>属性GoodState </summary>
        public System.Byte GoodState
        {
            get
            {
                return this.m_GoodState;
            }
            set
            {
                this.m_GoodState = value;
            }
        }

        /// <summary>属性IsTJ </summary>
        public System.Byte IsTJ
        {
            get
            {
                return this.m_IsTJ;
            }
            set
            {
                this.m_IsTJ = value;
            }
        }

        /// <summary>属性CreateDate </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this.m_CreateDate;
            }
            set
            {
                this.m_CreateDate = value;
            }
        }

        /// <summary>属性DetailUrl </summary>
        public string DetailUrl
        {
            get
            {
                return this.m_DetailUrl;
            }
            set
            {
                this.m_DetailUrl = value;
            }
        }

        /// <summary>����IsChecked </summary>
        public byte IsChecked
        {
            get
            {
                return this.m_IsChecked;
            }
            set
            {
                this.m_IsChecked = value;
            }
        }
    }

    /// XiHuan_UserGoodsEntity执行�?
    public abstract class XiHuan_UserGoodsEntityAction
    {

        private XiHuan_UserGoodsEntityAction()
        {
        }

        public static void Save(XiHuan_UserGoodsEntity obj)
        {
            if (obj != null)
            {
                obj.Save();
            }
        }

        /// <summary>根据主键获取一个实�?/summary>
        public static XiHuan_UserGoodsEntity RetrieveAXiHuan_UserGoodsEntity(int Id)
        {
            XiHuan_UserGoodsEntity obj = new XiHuan_UserGoodsEntity();
            obj.Id = Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }

        /// <summary>获取所有实�?EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_UserGoodsEntity()
        {
            RetrieveCriteria rc = new RetrieveCriteria(typeof(XiHuan_UserGoodsEntity));
            return rc.AsEntityContainer();
        }

        /// <summary>获取所有实�?EntityContainer)</summary>
        public static DataTable GetXiHuan_UserGoodsEntity()
        {
            RetrieveCriteria rc = new RetrieveCriteria(typeof(XiHuan_UserGoodsEntity));
            return rc.AsDataTable();
        }
    }
}
