//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Data;
    using PersistenceLayer;


    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_UserRequireEntity : EntityObject
    {

        /// <summary>Id</summary>
        public const string __ID = "Id";

        /// <summary>Id</summary>
        public const string __USERID = "UserId";
        /// <summary>Id</summary>
        public const string __USERNAME = "UserName";

        /// <summary>RequireType</summary>
        public const string __REQUIRETYPE = "RequireType";

        /// <summary>RequireContent</summary>
        public const string __REQUIRECONTENT = "RequireContent";

        /// <summary>ReuireDate</summary>
        public const string __REUIREDATE = "ReuireDate";

        /// <summary>IsChecked</summary>
        public const string __ISCHECKED = "IsChecked";

        private int m_Id;

        private int m_UserId;

        private string m_UserName;

        private byte m_RequireType;

        private string m_RequireContent;

        private System.DateTime m_ReuireDate = DateTime.MinValue;

        private byte m_IsChecked;

        /// <summary>构造函数</summary>
        public XiHuan_UserRequireEntity()
        {
        }

        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }

        /// <summary>属性UserId</summary>
        public int UserId
        {
            get
            {
                return this.m_UserId;
            }
            set
            {
                this.m_UserId = value;
            }
        }

        /// <summary>属性UserName </summary>
        public string UserName
        {
            get
            {
                return this.m_UserName;
            }
            set
            {
                this.m_UserName = value;
            }
        }

        /// <summary>属性RequireType </summary>
        public byte RequireType
        {
            get
            {
                return this.m_RequireType;
            }
            set
            {
                this.m_RequireType = value;
            }
        }

        /// <summary>属性RequireContent </summary>
        public string RequireContent
        {
            get
            {
                return this.m_RequireContent;
            }
            set
            {
                this.m_RequireContent = value;
            }
        }

        /// <summary>属性ReuireDate </summary>
        public System.DateTime ReuireDate
        {
            get
            {
                return this.m_ReuireDate;
            }
            set
            {
                this.m_ReuireDate = value;
            }
        }

        /// <summary>属性IsChecked </summary>
        public byte IsChecked
        {
            get
            {
                return this.m_IsChecked;
            }
            set
            {
                this.m_IsChecked = value;
            }
        }
    }

    /// XiHuan_UserRequireEntity执行类
    public abstract class XiHuan_UserRequireEntityAction
    {

        private XiHuan_UserRequireEntityAction()
        {
        }

        public static void Save(XiHuan_UserRequireEntity obj)
        {
            if (obj != null)
            {
                obj.Save();
            }
        }

        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_UserRequireEntity RetrieveAXiHuan_UserRequireEntity(int Id)
        {
            XiHuan_UserRequireEntity obj = new XiHuan_UserRequireEntity();
            obj.Id = Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }

        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_UserRequireEntity()
        {
            RetrieveCriteria rc = new RetrieveCriteria(typeof(XiHuan_UserRequireEntity));
            return rc.AsEntityContainer();
        }

        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_UserRequireEntity()
        {
            RetrieveCriteria rc = new RetrieveCriteria(typeof(XiHuan_UserRequireEntity));
            return rc.AsDataTable();
        }
    }
}
