//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-4-18 11:43:10
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_GoodsImageEntity : EntityObject
    {
        
        /// <summary>Id</summary>
        public const string __ID = "Id";
        
        /// <summary>GoodsId</summary>
        public const string __GOODSID = "GoodsId";
        
        /// <summary>GoodsName</summary>
        public const string __GOODSNAME = "GoodsName";
        
        /// <summary>ImgDesc</summary>
        public const string __IMGDESC = "ImgDesc";
        
        /// <summary>ImgSrc</summary>
        public const string __IMGSRC = "ImgSrc";
        
        /// <summary>IsDefaultPhoto</summary>
        public const string __ISDEFAULTPHOTO = "IsDefaultPhoto";
        
        /// <summary>CreateDate</summary>
        public const string __CREATEDATE = "CreateDate";
        
        private int m_Id;
        
        private int m_GoodsId;
        
        private string m_GoodsName;
        
        private string m_ImgDesc;
        
        private string m_ImgSrc;
        
        private System.Byte m_IsDefaultPhoto;
        
        private System.DateTime m_CreateDate = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public XiHuan_GoodsImageEntity()
        {
        }
        
        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }
        
        /// <summary>属性GoodsId </summary>
        public int GoodsId
        {
            get
            {
                return this.m_GoodsId;
            }
            set
            {
                this.m_GoodsId = value;
            }
        }
        
        /// <summary>属性GoodsName </summary>
        public string GoodsName
        {
            get
            {
                return this.m_GoodsName;
            }
            set
            {
                this.m_GoodsName = value;
            }
        }
        
        /// <summary>属性ImgDesc </summary>
        public string ImgDesc
        {
            get
            {
                return this.m_ImgDesc;
            }
            set
            {
                this.m_ImgDesc = value;
            }
        }
        
        /// <summary>属性ImgSrc </summary>
        public string ImgSrc
        {
            get
            {
                return this.m_ImgSrc;
            }
            set
            {
                this.m_ImgSrc = value;
            }
        }
        
        /// <summary>属性IsDefaultPhoto </summary>
        public System.Byte IsDefaultPhoto
        {
            get
            {
                return this.m_IsDefaultPhoto;
            }
            set
            {
                this.m_IsDefaultPhoto = value;
            }
        }
        
        /// <summary>属性CreateDate </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this.m_CreateDate;
            }
            set
            {
                this.m_CreateDate = value;
            }
        }
    }
    
    /// XiHuan_GoodsImageEntity执行类
    public abstract class XiHuan_GoodsImageEntityAction
    {
        
        private XiHuan_GoodsImageEntityAction()
        {
        }
        
        public static void Save(XiHuan_GoodsImageEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_GoodsImageEntity RetrieveAXiHuan_GoodsImageEntity(int Id)
        {
            XiHuan_GoodsImageEntity obj=new XiHuan_GoodsImageEntity();
            obj.Id=Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_GoodsImageEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_GoodsImageEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_GoodsImageEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_GoodsImageEntity));
            return rc.AsDataTable();
        }
    }
}
