//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_MessageEntity : EntityObject
    {
        
        /// <summary>Id</summary>
        public const string __ID = "Id";
        
        /// <summary>FromId</summary>
        public const string __FROMID = "FromId";
        
        /// <summary>ToId</summary>
        public const string __TOID = "ToId";
        
        /// <summary>FromName</summary>
        public const string __FROMNAME = "FromName";
        
        /// <summary>ToName</summary>
        public const string __TONAME = "ToName";
        
        /// <summary>Content</summary>
        public const string __CONTENT = "Content";
        
        /// <summary>Flag</summary>
        public const string __FLAG = "Flag";
        
        /// <summary>CreateDate</summary>
        public const string __CREATEDATE = "CreateDate";
        
        private int m_Id;
        
        private int m_FromId;
        
        private int m_ToId;
        
        private string m_FromName;
        
        private string m_ToName;
        
        private string m_Content;
        
        private byte m_Flag;
        
        private System.DateTime m_CreateDate = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public XiHuan_MessageEntity()
        {
        }
        
        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }
        
        /// <summary>属性FromId </summary>
        public int FromId
        {
            get
            {
                return this.m_FromId;
            }
            set
            {
                this.m_FromId = value;
            }
        }
        
        /// <summary>属性ToId </summary>
        public int ToId
        {
            get
            {
                return this.m_ToId;
            }
            set
            {
                this.m_ToId = value;
            }
        }
        
        /// <summary>属性FromName </summary>
        public string FromName
        {
            get
            {
                return this.m_FromName;
            }
            set
            {
                this.m_FromName = value;
            }
        }
        
        /// <summary>属性ToName </summary>
        public string ToName
        {
            get
            {
                return this.m_ToName;
            }
            set
            {
                this.m_ToName = value;
            }
        }
        
        /// <summary>属性Content </summary>
        public string Content
        {
            get
            {
                return this.m_Content;
            }
            set
            {
                this.m_Content = value;
            }
        }
        
        /// <summary>属性Flag </summary>
        public byte Flag
        {
            get
            {
                return this.m_Flag;
            }
            set
            {
                this.m_Flag = value;
            }
        }
        
        /// <summary>属性CreateDate </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this.m_CreateDate;
            }
            set
            {
                this.m_CreateDate = value;
            }
        }
    }
    
    /// XiHuan_MessageEntity执行类
    public abstract class XiHuan_MessageEntityAction
    {
        
        private XiHuan_MessageEntityAction()
        {
        }
        
        public static void Save(XiHuan_MessageEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_MessageEntity RetrieveAXiHuan_MessageEntity(int Id)
        {
            XiHuan_MessageEntity obj=new XiHuan_MessageEntity();
            obj.Id=Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_MessageEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_MessageEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_MessageEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_MessageEntity));
            return rc.AsDataTable();
        }
    }
}
