//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： tc01029
//             Created Time： 2009-3-31 17:28:07
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;


    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_UserInfoEntity : EntityObject
    {

        /// <summary>ID</summary>
        public const string @__ID = "ID";

        /// <summary>UserType</summary>
        public const string @__USERTYPE = "UserType";

        /// <summary>UserName</summary>
        public const string @__USERNAME = "UserName";

        /// <summary>Md5Pwd</summary>
        public const string @__MD5PWD = "Md5Pwd";

        /// <summary>OrignalPwd</summary>
        public const string @__ORIGNALPWD = "OrignalPwd";

        /// <summary>Gender</summary>
        public const string @__GENDER = "Gender";

        /// <summary>HeadImage</summary>
        public const string @__HEADIMAGE = "HeadImage";

        /// <summary>Email</summary>
        public const string @__EMAIL = "Email";

        /// <summary>
        /// TelePhone
        /// </summary>
        public const string @_TelePhone = "TelePhone";

        /// <summary>
        /// WangWang
        /// </summary>
        public const string @_WangWang = "WangWang";

        /// <summary>QQ</summary>
        public const string @__QQ = "QQ";

        /// <summary>Msn</summary>
        public const string @__MSN = "Msn";

        /// <summary>OtherLink</summary>
        public const string @__OTHERLINK = "OtherLink";

        /// <summary>ProvinceId</summary>
        public const string @__PROVINCEID = "ProvinceId";

        /// <summary>ProvinceName</summary>
        public const string @__PROVINCENAME = "ProvinceName";

        /// <summary>CityId</summary>
        public const string @__CITYID = "CityId";

        /// <summary>CityName</summary>
        public const string @__CITYNAME = "CityName";

        /// <summary>AreaId</summary>
        public const string @__AREAID = "AreaId";

        /// <summary>AreaName</summary>
        public const string @__AREANAME = "AreaName";

        /// <summary>SchoolId</summary>
        public const string @__SCHOOLID = "SchoolId";

        /// <summary>SchoolName</summary>
        public const string @__SCHOOLNAME = "SchoolName";

        /// <summary>SignNote</summary>
        public const string @__SignNote = "SignNote";

        /// <summary>HuanBi</summary>
        public const string @__HUANBI = "HuanBi";

        /// <summary>Score</summary>
        public const string @__SCORE = "Score";

        /// <summary>XinYu</summary>
        public const string @__XINYU = "XinYu";

        /// <summary>GoodFeed</summary>
        public const string @__GOODFEED = "GoodFeed";

        /// <summary>RegisterDate</summary>
        public const string @__REGISTERDATE = "RegisterDate";

        /// <summary>LastLoginTime</summary>
        public const string @__LASTLOGINTIME = "LastLoginTime";

        /// <summary>IsCertNoChecked</summary>
        public const string @__ISCERTNOCHECKED = "IsCertNoChecked";

        /// <summary>GoodsNumber</summary>
        public const string @__GOODSNUMBER = "GoodsNumber";

        /// <summary>IsStarUser</summary>
        public const string @__ISSTARUSER = "IsStarUser";

        /// <summary>Question</summary>
        public const string @__QUESTION = "Question";

        /// <summary>Answer</summary>
        public const string @__ANSWER = "Answer";

        /// <summary>IsLocked</summary>
        public const string @__ISLOCKED = "IsLocked";

        private int m_ID;

        private byte m_UserType;

        private string m_UserName;

        private string m_Md5Pwd;

        private string m_OrignalPwd;

        private byte m_Gender;

        private string m_HeadImage;

        private string m_Email;

        private string m_TelePhone;

        private string m_WangWang;

        private string m_QQ;

        private string m_Msn;

        private string m_OtherLink;

        private int m_ProvinceId;

        private string m_ProvinceName;

        private int m_CityId;

        private string m_CityName;

        private int m_AreaId;

        private string m_AreaName;

        private int m_SchoolId;

        private string m_SchoolName;

        private string m_SignNote;

        private int m_HuanBi;

        private int m_Score;

        private int m_XinYu;

        private int m_GoodFeed;

        private System.DateTime m_RegisterDate = DateTime.MinValue;

        private System.DateTime m_LastLoginTime = DateTime.MinValue;

        private byte m_IsCertNoChecked;

        private int m_GoodsNumber;

        private byte m_IsStarUser;

        private string m_Question;

        private string m_Answer;

        private byte m_IsLocked;

        /// <summary>构造函数</summary>
        public XiHuan_UserInfoEntity()
        {
        }

        /// <summary>属性ID </summary>
        public int ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }

        /// <summary>属性UserType </summary>
        public byte UserType
        {
            get
            {
                return this.m_UserType;
            }
            set
            {
                this.m_UserType = value;
            }
        }

        /// <summary>属性UserName </summary>
        public string UserName
        {
            get
            {
                return this.m_UserName;
            }
            set
            {
                this.m_UserName = value;
            }
        }

        /// <summary>属性Md5Pwd </summary>
        public string Md5Pwd
        {
            get
            {
                return this.m_Md5Pwd;
            }
            set
            {
                this.m_Md5Pwd = value;
            }
        }

        /// <summary>属性OrignalPwd </summary>
        public string OrignalPwd
        {
            get
            {
                return this.m_OrignalPwd;
            }
            set
            {
                this.m_OrignalPwd = value;
            }
        }

        /// <summary>属性Gender </summary>
        public byte Gender
        {
            get
            {
                return this.m_Gender;
            }
            set
            {
                this.m_Gender = value;
            }
        }

        /// <summary>属性HeadImage </summary>
        public string HeadImage
        {
            get
            {
                return this.m_HeadImage;
            }
            set
            {
                this.m_HeadImage = value;
            }
        }

        /// <summary>属性Email </summary>
        public string Email
        {
            get
            {
                return this.m_Email;
            }
            set
            {
                this.m_Email = value;
            }
        }

        /// <summary>属性TelePhone </summary>
        public string TelePhone
        {
            get
            {
                return this.m_TelePhone;
            }
            set
            {
                this.m_TelePhone = value;
            }
        }

        /// <summary>
        /// 属性WangWang
        /// </summary>
        public string WangWang
        {
            get
            {
                return this.m_WangWang;
            }
            set
            {
                this.m_WangWang = value;
            }
        }

        /// <summary>属性QQ </summary>
        public string QQ
        {
            get
            {
                return this.m_QQ;
            }
            set
            {
                this.m_QQ = value;
            }
        }

        /// <summary>属性Msn </summary>
        public string Msn
        {
            get
            {
                return this.m_Msn;
            }
            set
            {
                this.m_Msn = value;
            }
        }

        /// <summary>属性OtherLink </summary>
        public string OtherLink
        {
            get
            {
                return this.m_OtherLink;
            }
            set
            {
                this.m_OtherLink = value;
            }
        }

        /// <summary>属性ProvinceId </summary>
        public int ProvinceId
        {
            get
            {
                return this.m_ProvinceId;
            }
            set
            {
                this.m_ProvinceId = value;
            }
        }

        /// <summary>属性ProvinceName </summary>
        public string ProvinceName
        {
            get
            {
                return this.m_ProvinceName;
            }
            set
            {
                this.m_ProvinceName = value;
            }
        }

        /// <summary>属性CityId </summary>
        public int CityId
        {
            get
            {
                return this.m_CityId;
            }
            set
            {
                this.m_CityId = value;
            }
        }

        /// <summary>属性CityName </summary>
        public string CityName
        {
            get
            {
                return this.m_CityName;
            }
            set
            {
                this.m_CityName = value;
            }
        }

        /// <summary>属性AreaId </summary>
        public int AreaId
        {
            get
            {
                return this.m_AreaId;
            }
            set
            {
                this.m_AreaId = value;
            }
        }

        /// <summary>属性AreaName </summary>
        public string AreaName
        {
            get
            {
                return this.m_AreaName;
            }
            set
            {
                this.m_AreaName = value;
            }
        }

        /// <summary>属性SchoolId </summary>
        public int SchoolId
        {
            get
            {
                return this.m_SchoolId;
            }
            set
            {
                this.m_SchoolId = value;
            }
        }

        /// <summary>属性SchoolName </summary>
        public string SchoolName
        {
            get
            {
                return this.m_SchoolName;
            }
            set
            {
                this.m_SchoolName = value;
            }
        }

        /// <summary>属性SignNote </summary>
        public string SignNote
        {
            get
            {
                return this.m_SignNote;
            }
            set
            {
                this.m_SignNote = value;
            }
        }

        /// <summary>属性HuanBi </summary>
        public int HuanBi
        {
            get
            {
                return this.m_HuanBi;
            }
            set
            {
                this.m_HuanBi = value;
            }
        }

        /// <summary>属性Score </summary>
        public int Score
        {
            get
            {
                return this.m_Score;
            }
            set
            {
                this.m_Score = value;
            }
        }

        /// <summary>属性XinYu </summary>
        public int XinYu
        {
            get
            {
                return this.m_XinYu;
            }
            set
            {
                this.m_XinYu = value;
            }
        }

        /// <summary>属性GoodFeed </summary>
        public int GoodFeed
        {
            get
            {
                return this.m_GoodFeed;
            }
            set
            {
                this.m_GoodFeed = value;
            }
        }

        /// <summary>属性RegisterDate </summary>
        public System.DateTime RegisterDate
        {
            get
            {
                return this.m_RegisterDate;
            }
            set
            {
                this.m_RegisterDate = value;
            }
        }

        /// <summary>属性LastLoginTime </summary>
        public System.DateTime LastLoginTime
        {
            get
            {
                return this.m_LastLoginTime;
            }
            set
            {
                this.m_LastLoginTime = value;
            }
        }

        /// <summary>属性IsCertNoChecked </summary>
        public byte IsCertNoChecked
        {
            get
            {
                return this.m_IsCertNoChecked;
            }
            set
            {
                this.m_IsCertNoChecked = value;
            }
        }

        /// <summary>属性GoodsNumber </summary>
        public int GoodsNumber
        {
            get
            {
                return this.m_GoodsNumber;
            }
            set
            {
                this.m_GoodsNumber = value;
            }
        }

        /// <summary>属性IsStarUser </summary>
        public byte IsStarUser
        {
            get
            {
                return this.m_IsStarUser;
            }
            set
            {
                this.m_IsStarUser = value;
            }
        }

        /// <summary>属性Question </summary>
        public string Question
        {
            get
            {
                return this.m_Question;
            }
            set
            {
                this.m_Question = value;
            }
        }

        /// <summary>属性Answer </summary>
        public string Answer
        {
            get
            {
                return this.m_Answer;
            }
            set
            {
                this.m_Answer = value;
            }
        }

        /// <summary>属性IsLocked </summary>
        public byte IsLocked
        {
            get
            {
                return this.m_IsLocked;
            }
            set
            {
                this.m_IsLocked = value;
            }
        }
    }

    /// XiHuan_UserInfoEntity执行类
    public abstract class XiHuan_UserInfoEntityAction
    {

        private XiHuan_UserInfoEntityAction()
        {
        }

        public static void Save(XiHuan_UserInfoEntity obj)
        {
            if (obj != null)
            {
                obj.Save();
            }
        }

        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_UserInfoEntity RetrieveAXiHuan_UserInfoEntity(int ID)
        {
            XiHuan_UserInfoEntity obj = new XiHuan_UserInfoEntity();
            obj.ID = ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }

        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_UserInfoEntity()
        {
            RetrieveCriteria rc = new RetrieveCriteria(typeof(XiHuan_UserInfoEntity));
            return rc.AsEntityContainer();
        }

        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_UserInfoEntity()
        {
            RetrieveCriteria rc = new RetrieveCriteria(typeof(XiHuan_UserInfoEntity));
            return rc.AsDataTable();
        }
    }
}
