//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_UserFavorateEntity : EntityObject
    {
        
        /// <summary>Id</summary>
        public const string __ID = "Id";
        
        /// <summary>UserId</summary>
        public const string __USERID = "UserId";
        
        /// <summary>GoodsId</summary>
        public const string __GOODSID = "GoodsId";
        
        /// <summary>GoodsName</summary>
        public const string __GOODSNAME = "GoodsName";
        
        /// <summary>FavDate</summary>
        public const string __FAVDATE = "FavDate";
        
        /// <summary>FacRemark</summary>
        public const string __FACREMARK = "FacRemark";
        
        private int m_Id;
        
        private int m_UserId;
        
        private int m_GoodsId;
        
        private string m_GoodsName;
        
        private System.DateTime m_FavDate = DateTime.MinValue;
        
        private string m_FacRemark;
        
        /// <summary>构造函数</summary>
        public XiHuan_UserFavorateEntity()
        {
        }
        
        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }
        
        /// <summary>属性UserId </summary>
        public int UserId
        {
            get
            {
                return this.m_UserId;
            }
            set
            {
                this.m_UserId = value;
            }
        }
        
        /// <summary>属性GoodsId </summary>
        public int GoodsId
        {
            get
            {
                return this.m_GoodsId;
            }
            set
            {
                this.m_GoodsId = value;
            }
        }
        
        /// <summary>属性GoodsName </summary>
        public string GoodsName
        {
            get
            {
                return this.m_GoodsName;
            }
            set
            {
                this.m_GoodsName = value;
            }
        }
        
        /// <summary>属性FavDate </summary>
        public System.DateTime FavDate
        {
            get
            {
                return this.m_FavDate;
            }
            set
            {
                this.m_FavDate = value;
            }
        }
        
        /// <summary>属性FacRemark </summary>
        public string FacRemark
        {
            get
            {
                return this.m_FacRemark;
            }
            set
            {
                this.m_FacRemark = value;
            }
        }
    }
    
    /// XiHuan_UserFavorateEntity执行类
    public abstract class XiHuan_UserFavorateEntityAction
    {
        
        private XiHuan_UserFavorateEntityAction()
        {
        }
        
        public static void Save(XiHuan_UserFavorateEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_UserFavorateEntity RetrieveAXiHuan_UserFavorateEntity(int Id)
        {
            XiHuan_UserFavorateEntity obj=new XiHuan_UserFavorateEntity();
            obj.Id=Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_UserFavorateEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_UserFavorateEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_UserFavorateEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_UserFavorateEntity));
            return rc.AsDataTable();
        }
    }
}
