//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_GoodsSecondTypeEntity : EntityObject
    {
        
        /// <summary>Id</summary>
        public const string __ID = "Id";
        
        /// <summary>ParentId</summary>
        public const string __PARENTID = "ParentId";
        
        /// <summary>Name</summary>
        public const string __NAME = "Name";
        
        /// <summary>CreateDate</summary>
        public const string __CREATEDATE = "CreateDate";
        
        private int m_Id;
        
        private int m_ParentId;
        
        private string m_Name;
        
        private System.DateTime m_CreateDate = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public XiHuan_GoodsSecondTypeEntity()
        {
        }
        
        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }
        
        /// <summary>属性ParentId </summary>
        public int ParentId
        {
            get
            {
                return this.m_ParentId;
            }
            set
            {
                this.m_ParentId = value;
            }
        }
        
        /// <summary>属性Name </summary>
        public string Name
        {
            get
            {
                return this.m_Name;
            }
            set
            {
                this.m_Name = value;
            }
        }
        
        /// <summary>属性CreateDate </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this.m_CreateDate;
            }
            set
            {
                this.m_CreateDate = value;
            }
        }
    }
    
    /// XiHuan_GoodsSecondTypeEntity执行类
    public abstract class XiHuan_GoodsSecondTypeEntityAction
    {
        
        private XiHuan_GoodsSecondTypeEntityAction()
        {
        }
        
        public static void Save(XiHuan_GoodsSecondTypeEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_GoodsSecondTypeEntity RetrieveAXiHuan_GoodsSecondTypeEntity(int Id)
        {
            XiHuan_GoodsSecondTypeEntity obj=new XiHuan_GoodsSecondTypeEntity();
            obj.Id=Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_GoodsSecondTypeEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_GoodsSecondTypeEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_GoodsSecondTypeEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_GoodsSecondTypeEntity));
            return rc.AsDataTable();
        }
    }
}
