//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2009-3-28 17:03:34
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class XiHuan_SchoolInfoEntity : EntityObject
    {
        
        /// <summary>Id</summary>
        public const string __ID = "Id";
        
        /// <summary>SchoolName</summary>
        public const string __SCHOOLNAME = "SchoolName";
        
        /// <summary>ProvinceId</summary>
        public const string __PROVINCEID = "ProvinceId";
        
        /// <summary>CityId</summary>
        public const string __CITYID = "CityId";
        
        /// <summary>AreaId</summary>
        public const string __AREAID = "AreaId";
        
        private int m_Id;
        
        private string m_SchoolName;
        
        private int m_ProvinceId;
        
        private int m_CityId;
        
        private int m_AreaId;
        
        /// <summary>构造函数</summary>
        public XiHuan_SchoolInfoEntity()
        {
        }
        
        /// <summary>属性Id </summary>
        public int Id
        {
            get
            {
                return this.m_Id;
            }
            set
            {
                this.m_Id = value;
            }
        }
        
        /// <summary>属性SchoolName </summary>
        public string SchoolName
        {
            get
            {
                return this.m_SchoolName;
            }
            set
            {
                this.m_SchoolName = value;
            }
        }
        
        /// <summary>属性ProvinceId </summary>
        public int ProvinceId
        {
            get
            {
                return this.m_ProvinceId;
            }
            set
            {
                this.m_ProvinceId = value;
            }
        }
        
        /// <summary>属性CityId </summary>
        public int CityId
        {
            get
            {
                return this.m_CityId;
            }
            set
            {
                this.m_CityId = value;
            }
        }
        
        /// <summary>属性AreaId </summary>
        public int AreaId
        {
            get
            {
                return this.m_AreaId;
            }
            set
            {
                this.m_AreaId = value;
            }
        }
    }
    
    /// XiHuan_SchoolInfoEntity执行类
    public abstract class XiHuan_SchoolInfoEntityAction
    {
        
        private XiHuan_SchoolInfoEntityAction()
        {
        }
        
        public static void Save(XiHuan_SchoolInfoEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static XiHuan_SchoolInfoEntity RetrieveAXiHuan_SchoolInfoEntity(int Id)
        {
            XiHuan_SchoolInfoEntity obj=new XiHuan_SchoolInfoEntity();
            obj.Id=Id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveXiHuan_SchoolInfoEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_SchoolInfoEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetXiHuan_SchoolInfoEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(XiHuan_SchoolInfoEntity));
            return rc.AsDataTable();
        }
    }
}
